#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("WydatkiAnd.Resource", IsApplication=true)]

namespace WydatkiAnd
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070044
			public const int AddBtn = 2131165252;
			
			// aapt resource value: 0x7f070051
			public const int ExpGrid = 2131165265;
			
			// aapt resource value: 0x7f070040
			public const int Grid = 2131165248;
			
			// aapt resource value: 0x7f070056
			public const int IncGrid = 2131165270;
			
			// aapt resource value: 0x7f070045
			public const int ReportsBtn = 2131165253;
			
			// aapt resource value: 0x7f070010
			public const int addExpenseBtn = 2131165200;
			
			// aapt resource value: 0x7f07001e
			public const int addHost = 2131165214;
			
			// aapt resource value: 0x7f07001d
			public const int addIncomeBtn = 2131165213;
			
			// aapt resource value: 0x7f070024
			public const int btnAddCat = 2131165220;
			
			// aapt resource value: 0x7f07000f
			public const int btnCategories = 2131165199;
			
			// aapt resource value: 0x7f07004e
			public const int btnChangeEstBills = 2131165262;
			
			// aapt resource value: 0x7f07004b
			public const int btnChangeMonthLimit = 2131165259;
			
			// aapt resource value: 0x7f070026
			public const int btnDelCat = 2131165222;
			
			// aapt resource value: 0x7f070028
			public const int btnEditCat = 2131165224;
			
			// aapt resource value: 0x7f070033
			public const int btnExpenseEdit = 2131165235;
			
			// aapt resource value: 0x7f070023
			public const int editAddCat = 2131165219;
			
			// aapt resource value: 0x7f070027
			public const int editEditCat = 2131165223;
			
			// aapt resource value: 0x7f070058
			public const int editEndDate = 2131165272;
			
			// aapt resource value: 0x7f070020
			public const int editEstBills = 2131165216;
			
			// aapt resource value: 0x7f070053
			public const int editExpEndDate = 2131165267;
			
			// aapt resource value: 0x7f070052
			public const int editExpStartDate = 2131165266;
			
			// aapt resource value: 0x7f070004
			public const int editExpenseAmount = 2131165188;
			
			// aapt resource value: 0x7f07002c
			public const int editExpenseAmountDialog = 2131165228;
			
			// aapt resource value: 0x7f070007
			public const int editExpenseDate = 2131165191;
			
			// aapt resource value: 0x7f07002a
			public const int editExpenseDateDialog = 2131165226;
			
			// aapt resource value: 0x7f07000a
			public const int editExpenseDetails = 2131165194;
			
			// aapt resource value: 0x7f07002e
			public const int editExpenseDetailsDialog = 2131165230;
			
			// aapt resource value: 0x7f070015
			public const int editIncomeAmount = 2131165205;
			
			// aapt resource value: 0x7f07003c
			public const int editIncomeAmountDialog = 2131165244;
			
			// aapt resource value: 0x7f070019
			public const int editIncomeDate = 2131165209;
			
			// aapt resource value: 0x7f07003a
			public const int editIncomeDateDialog = 2131165242;
			
			// aapt resource value: 0x7f07001c
			public const int editIncomeDetails = 2131165212;
			
			// aapt resource value: 0x7f07003e
			public const int editIncomeDetailsDialog = 2131165246;
			
			// aapt resource value: 0x7f070022
			public const int editLimit = 2131165218;
			
			// aapt resource value: 0x7f070057
			public const int editStartDate = 2131165271;
			
			// aapt resource value: 0x7f070035
			public const int expRowGrid = 2131165237;
			
			// aapt resource value: 0x7f070036
			public const int expenseRowText1 = 2131165238;
			
			// aapt resource value: 0x7f070037
			public const int expenseRowText2 = 2131165239;
			
			// aapt resource value: 0x7f070038
			public const int expenseRowText3 = 2131165240;
			
			// aapt resource value: 0x7f070055
			public const int expensesList = 2131165269;
			
			// aapt resource value: 0x7f070041
			public const int incomeRowText1 = 2131165249;
			
			// aapt resource value: 0x7f070042
			public const int incomeRowText2 = 2131165250;
			
			// aapt resource value: 0x7f070043
			public const int incomeRowText3 = 2131165251;
			
			// aapt resource value: 0x7f070059
			public const int incomesList = 2131165273;
			
			// aapt resource value: 0x7f07000d
			public const int linearLayout1 = 2131165197;
			
			// aapt resource value: 0x7f070000
			public const int mainScrollView = 2131165184;
			
			// aapt resource value: 0x7f07003f
			public const int relativeLayout11 = 2131165247;
			
			// aapt resource value: 0x7f070034
			public const int relativeLayout111 = 2131165236;
			
			// aapt resource value: 0x7f07004f
			public const int reportsToolbar = 2131165263;
			
			// aapt resource value: 0x7f070050
			public const int showHost = 2131165264;
			
			// aapt resource value: 0x7f07000e
			public const int spinnerCategory = 2131165198;
			
			// aapt resource value: 0x7f070025
			public const int spinnerEditCat = 2131165221;
			
			// aapt resource value: 0x7f070032
			public const int spinnerExpenseEdit = 2131165234;
			
			// aapt resource value: 0x7f070054
			public const int spinnerShowExp = 2131165268;
			
			// aapt resource value: 0x7f070011
			public const int tableLayout1 = 2131165201;
			
			// aapt resource value: 0x7f070001
			public const int tableLayout2 = 2131165185;
			
			// aapt resource value: 0x7f070012
			public const int tableRow1 = 2131165202;
			
			// aapt resource value: 0x7f070014
			public const int tableRow2 = 2131165204;
			
			// aapt resource value: 0x7f070002
			public const int tableRow21 = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int tableRow22 = 2131165187;
			
			// aapt resource value: 0x7f070005
			public const int tableRow23 = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int tableRow24 = 2131165190;
			
			// aapt resource value: 0x7f070008
			public const int tableRow25 = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int tableRow26 = 2131165193;
			
			// aapt resource value: 0x7f07000b
			public const int tableRow27 = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int tableRow28 = 2131165196;
			
			// aapt resource value: 0x7f070016
			public const int tableRow3 = 2131165206;
			
			// aapt resource value: 0x7f070018
			public const int tableRow4 = 2131165208;
			
			// aapt resource value: 0x7f07001a
			public const int tableRow5 = 2131165210;
			
			// aapt resource value: 0x7f07001b
			public const int tableRow6 = 2131165211;
			
			// aapt resource value: 0x7f070047
			public const int textBalance = 2131165255;
			
			// aapt resource value: 0x7f07004c
			public const int textEstBills = 2131165260;
			
			// aapt resource value: 0x7f07004d
			public const int textEstBillsShow = 2131165261;
			
			// aapt resource value: 0x7f070049
			public const int textMonthLimit = 2131165257;
			
			// aapt resource value: 0x7f07004a
			public const int textMonthLimitShow = 2131165258;
			
			// aapt resource value: 0x7f070048
			public const int textPlusMinus = 2131165256;
			
			// aapt resource value: 0x7f070021
			public const int textView1 = 2131165217;
			
			// aapt resource value: 0x7f070039
			public const int textView12 = 2131165241;
			
			// aapt resource value: 0x7f070029
			public const int textView123 = 2131165225;
			
			// aapt resource value: 0x7f07003b
			public const int textView13 = 2131165243;
			
			// aapt resource value: 0x7f07002b
			public const int textView133 = 2131165227;
			
			// aapt resource value: 0x7f07003d
			public const int textView14 = 2131165245;
			
			// aapt resource value: 0x7f07002d
			public const int textView143 = 2131165229;
			
			// aapt resource value: 0x7f07002f
			public const int textView144 = 2131165231;
			
			// aapt resource value: 0x7f070030
			public const int textView145 = 2131165232;
			
			// aapt resource value: 0x7f070031
			public const int textView146 = 2131165233;
			
			// aapt resource value: 0x7f07001f
			public const int textView2 = 2131165215;
			
			// aapt resource value: 0x7f070013
			public const int textView321 = 2131165203;
			
			// aapt resource value: 0x7f070017
			public const int textView322 = 2131165207;
			
			// aapt resource value: 0x7f070046
			public const int textWelcome = 2131165254;
			
			// aapt resource value: 0x7f07005a
			public const int toolbar = 2131165274;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddExpenseView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AddIncomeView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int AddView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ChangeEstBillsView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ChangeLimitView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int EditCategoriesView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ExpenseDetailsView = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int ExpenseListRow = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int IncomeDetailsDialogView = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int IncomeListRow = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Main = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int reportsToolbar = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int ReportsView = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int ShowExpensesView = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int ShowIncomesView = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int toolbar = 2130903055;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int Wydatkidb = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int Welcome = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int MyTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
